name: payflow
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^1.8.0
  flutter:
    sdk: flutter
  get: ^4.1.4
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  google_sign_in: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
